spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zuobiji?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: fengweim
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
